name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: module

      - name: Make Release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          generateReleaseNotes: true
          artifacts: "module.zip,dist/module.json"
